project:
  type: website
  output-dir: docs

website:
  title: "Karan Homayounfar"
  site-url: https://knhf.github.io
  description: "Personal portfolio and data science projects"
  sidebar: false
  page-navigation: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: contact.qmd
        text: Contact
    right:
      - icon: github
        href: https://github.com/knhf
      - icon: linkedin
        href: https://www.linkedin.com/in/karen-homayounfar-96824893/

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: false