project:
  type: website
  output-dir: docs
  
website:
  title: "Karan Homayounfar"
  site-url: https://knhf.github.io
  description: "Personal portfolio and data science projects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
    right:
      - icon: github
        href: https://github.com/knhf
        
format:
  html:
    theme:
      - vapor
      - brand
    css: styles.css



